### ISSUE TITLE
Connect via MAC address

### ISSUE THREAD

**Issue by xoac** [go-routeros/routeros#12]
Hi, 
Winbox and [mactelnet](https://github.com/haakonnessjoen/MAC-Telnet) can connect to mikrotik with MAC address. It is possible to add such functionality?

**Comment by archaron** [comment]
Thank you for your issue, this is a quite interesting thing to implement. I'll try to investigate it to see if I can find a simple solution.

**Comment by archaron** [comment]
After some investigation, I found the following:
Tools/MAC Server menu item allows us to enable:
- MAC WinBox Server
- MAC Telnet Server
- MAC Ping Server

And there is no way to enable somehow MAC API Server. 

On your screen, there is neighbor discovery & **WinBox** connection. But this project is about **API**.

If you can find any information on how to enable the MAC API connection, I will try to implement it.

**Comment by rifatdinc** [comment]
it is not possible to use anything that requires something interactive through API. As result no telnet, mac-telnet, api login to other router etc.

If you want to automate these interactive things (mac-telnet) you should look at expect scripts and TCL that are specifically designed to imitate user interaction with them.
