### ISSUE TITLE
Login method is deprecated and no longer supported in versions above 6.45.1.

### ISSUE THREAD

**Issue by firdavsich** [go-routeros/routeros#13]
Please change login method for supporting routeros 6.45.1 and newer:
https://wiki.mikrotik.com/wiki/Manual:API#Initial_login

**Comment by wildsurfer** [comment]
+1

**Comment by wildsurfer** [comment]
Seems to be already fixed in https://github.com/go-routeros/routeros/pull/4

**Comment by andre-luiz-dos-santos** [comment]
Implemented by @archaron in #4.
