### ISSUE TITLE
[question] how to modify code for reuterOS v6

### ISSUE THREAD

**Issue by m3dbedb** [go-routeros/routeros#20]
For API v6 request **/ip/firewall/address-list/listen** looks like **/ip firewall address-list listen**

when I change line 13 master/examples/listen/main.go

to 

    command  = flag.String("command", "/ip firewall address-list listen", "RouterOS command")

I have error

    from RouterOS device: no such command
    exit status 1

**Comment by archaron** [comment]
Is this issue resolved for you?

**Comment by m3dbedb** [comment]
I don't remember, let's say "It works".
